title: Your awesome title

# You'll want to customize url and baseurl for your own site:
# baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site

name: AdLucem
markdown: kramdown
